// Generated by scripts/generate-i18n-catalogs.cjs. Edit the registry and language JSON files.
import catalog0 from "../../electron/locales/zh-CN.json";
import catalog1 from "../../electron/locales/en-US.json";
export const catalogs = { "zh-CN": catalog0, "en-US": catalog1 };
export const LANGUAGES = [
  {
    "id": "zh-CN",
    "name": "简体中文",
    "direction": "ltr"
  },
  {
    "id": "en-US",
    "name": "English",
    "direction": "ltr"
  }
] as const;
export const BASE_LANGUAGE = "zh-CN" as const;
