import { useLocale } from "../../i18n/react";
import { t } from "../../i18n/runtime";
import { useEffect, useMemo, useRef, useState } from 'react';
import { readPageTransferValue, usePageTransferParticipant } from '../../platform/page-transfer-state';
import { useHostSurfaceSuspension } from '../../components/LayerProvider';
import { ComponentIcon } from '../../components/ComponentIcon';
import type { ComponentContribution, ComponentPageOpenScope, WorkspaceProject } from '../../types';
import { componentPanelTaskKind, type PanelTaskRestoreDetail } from '../background-tasks/panel-task-session-model';
import { clampCommandIndex, nextCommandIndex, shouldRegisterCommandShortcut } from './component-command-palette-model';
import { ComponentToolPanelSurface } from './ComponentToolPanelSurface';

type Opened = { contribution: ComponentContribution; instanceId: string; contentHeight?: number };
export const ComponentContributionDock = ({ contributions, project, workspacePath = '', scope = { scopeRelativePath: '', selectedRelativePaths: [], sourcePageId: '' }, active = true }: { contributions: ComponentContribution[]; project?: WorkspaceProject; workspacePath?: string; scope?: ComponentPageOpenScope; active?: boolean }) => {
  useLocale();
  const [opened, setOpened] = useState<Opened | null>(null); const openedRef = useRef<Opened | null>(null); const openGeneration = useRef(0); const [componentPanelOpen, setComponentPanelOpen] = useState(false); const [commandsOpen, setCommandsOpen] = useState(false); const [query, setQuery] = useState(''); const [activeCommandIndex, setActiveCommandIndex] = useState(-1); const panelRef = useRef<HTMLDivElement>(null); const focusBeforeCommand = useRef<HTMLElement | null>(null); const [width, setWidth] = useState(360);
  useHostSurfaceSuspension(commandsOpen);
  const restoredDock = useRef(false);
  const transferPageId = usePageTransferParticipant('componentDock', { read: () => ({ opened, componentPanelOpen, width }) });
  useEffect(() => {
    if (restoredDock.current) return;
    const saved = readPageTransferValue<{ opened: Opened | null; componentPanelOpen: boolean; width: number } | null>(transferPageId, 'componentDock', () => null);
    if (!saved?.opened || saved.opened.contribution.placement === 'workspace.folderPanel' || !contributions.some(item => item.componentId === saved.opened!.contribution.componentId && item.contributionId === saved.opened!.contribution.contributionId)) return;
    restoredDock.current = true; openedRef.current = saved.opened;
    setOpened(saved.opened); setComponentPanelOpen(saved.componentPanelOpen); setWidth(saved.width);
  }, [contributions, transferPageId]);
  const projectEntries = project ? contributions.filter(item => ['component.sidePanel', 'project.contextAction', 'project.exportProvider'].includes(item.type) && !item.placement) : []; const commands = contributions.filter(item => item.type === 'application.command'); const filtered = useMemo(() => commands.filter(item => item.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [commands, query]); const resolvedCommandIndex = clampCommandIndex(activeCommandIndex, filtered.length);
  const open = async (contribution: ComponentContribution, triggerScope = scope) => {
    if (contribution.placement === 'workspace.folderPanel') return;
    const application = contribution.type === 'application.command'; if (!application && !project) return;
    const generation = ++openGeneration.current;
    try {
      const result = await window.electronAPI.openComponentContribution({ componentId: contribution.componentId, contributionId: contribution.contributionId, type: contribution.type, ...(application ? {} : { workspacePath, projectId: project!.id, projectName: project!.name, projectStatus: project!.status, ...triggerScope }) }).catch(() => ({ success: false, page: undefined }));
      if (generation !== openGeneration.current || !active) { if (result.page?.instanceId) void window.electronAPI.closeComponentPage(result.page.instanceId).catch(() => undefined); return; }
      if (!result.success || !result.page) return;
      const previous = openedRef.current;
      if (previous?.instanceId && previous.instanceId !== result.page.instanceId) void window.electronAPI.closeComponentPage(previous.instanceId).catch(() => undefined);
      const next = { contribution, instanceId: result.page.instanceId, contentHeight: result.page.contentHeight };
      openedRef.current = next; setOpened(next); setComponentPanelOpen(contribution.type === 'component.sidePanel'); closeCommands();
    } catch { /* Opening failed or the owner page closed. */ }
  };
  const showCommands = () => { focusBeforeCommand.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setQuery(''); setActiveCommandIndex(0); setCommandsOpen(true); };
  const closeCommands = () => { setCommandsOpen(false); window.requestAnimationFrame(() => focusBeforeCommand.current?.focus()); };
  useEffect(() => { if (!active || !shouldRegisterCommandShortcut(commands.length)) return; const listener = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLocaleLowerCase() === 'p') { event.preventDefault(); if (commandsOpen) closeCommands(); else showCommands(); } else if (event.key === 'Escape' && commandsOpen) closeCommands(); }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); });
  useEffect(() => { if (!active) { openGeneration.current += 1; setCommandsOpen(false); } }, [active]);
  useEffect(() => { if (!commands.length) setCommandsOpen(false); }, [commands.length]);
  useEffect(() => { setActiveCommandIndex(current => clampCommandIndex(current, filtered.length)); }, [filtered.length]);
  useEffect(() => { const listener = (event: Event) => { const detail = (event as CustomEvent<{ contribution: ComponentContribution; scope?: ComponentPageOpenScope }>).detail; if (active && detail?.contribution && (!detail.scope?.sourcePageId || detail.scope.sourcePageId === scope.sourcePageId)) void open(detail.contribution, detail.scope || scope); }; window.addEventListener('photoflow:open-component-contribution', listener); return () => window.removeEventListener('photoflow:open-component-contribution', listener); });
  useEffect(() => { const listener = (event: Event) => { const detail = (event as CustomEvent<PanelTaskRestoreDetail>).detail; if (!active || detail?.ownerPageId !== scope.sourcePageId || !detail.panelKind) return; const contribution = contributions.find(item => item.type === 'component.sidePanel' && componentPanelTaskKind(item.componentId, item.contributionId) === detail.panelKind); if (!contribution) return; if (opened?.contribution.componentId === contribution.componentId && opened.contribution.contributionId === contribution.contributionId) setComponentPanelOpen(true); else void open(contribution, scope); }; window.addEventListener('photoflow:restore-panel-task', listener); return () => window.removeEventListener('photoflow:restore-panel-task', listener); });
  useEffect(() => { if (!opened?.instanceId || opened.contribution.type === 'component.sidePanel') return; const instanceId=opened.instanceId; const element = panelRef.current; let frame=0; const update = () => { frame=0; if (!active || !element) { void window.electronAPI.setComponentPageBounds(instanceId, { x: 0, y: 0, width: 0, height: 0 }).catch(() => undefined); return; } const bounds = element.getBoundingClientRect(); void window.electronAPI.setComponentPageBounds(instanceId, { x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height }).catch(() => undefined); }; const schedule=()=>{if(!frame)frame=window.requestAnimationFrame(update);}; if (!active) { update(); void window.electronAPI.activateComponentPage({ instanceId: '' }).catch(() => undefined); return; } const observer = new ResizeObserver(schedule); if(element)observer.observe(element); window.addEventListener('resize',schedule); window.addEventListener('scroll',schedule,true); void window.electronAPI.activateComponentPage({instanceId}).catch(() => undefined); schedule(); return () => { observer.disconnect(); window.removeEventListener('resize',schedule); window.removeEventListener('scroll',schedule,true); if(frame)window.cancelAnimationFrame(frame); void window.electronAPI.setComponentPageBounds(instanceId, { x: 0, y: 0, width: 0, height: 0 }).catch(() => undefined); }; }, [active, opened, width]);
  useEffect(() => { openedRef.current = opened; }, [opened]);
  useEffect(() => () => { openGeneration.current += 1; if (openedRef.current?.instanceId) void window.electronAPI.closeComponentPage(openedRef.current.instanceId).catch(() => undefined); }, []);
  useEffect(() => { if (opened && !contributions.some(item => item.componentId === opened.contribution.componentId && item.componentVersion === opened.contribution.componentVersion && item.contributionId === opened.contribution.contributionId)) { openGeneration.current += 1; void window.electronAPI.closeComponentPage(opened.instanceId).catch(() => undefined); setOpened(null); } }, [contributions, opened]);
  if (!projectEntries.length && !commands.length && !opened) return null;
  return <><div className="flex items-center gap-1" aria-label={t("ui.plugin.entries.b57ce7")}>{projectEntries.map(item => <button key={`${item.componentId}:${item.contributionId}`} type="button" className="inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-2 py-1 text-xs font-semibold text-slate-600 hover:bg-slate-50" title={`${item.type} · ${item.title}`} onClick={() => void open(item)}><ComponentIcon src={item.iconUrl} size={14}/>{item.type === 'project.exportProvider' ? t("ui.export.6de351") : item.type === 'component.sidePanel' ? t("ui.panel.b8263c") : ''}{item.label}</button>)}{commands.length > 0 && <button type="button" aria-haspopup="dialog" className="rounded-md border border-slate-200 bg-white px-2 py-1 text-xs font-semibold text-slate-600" onClick={showCommands}>{t("ui.commands.c7de3a")}</button>}</div>
    {opened?.contribution.type === 'component.sidePanel' && <ComponentToolPanelSurface
      contribution={opened.contribution}
      instanceId={opened.instanceId}
      initialContentHeight={opened.contentHeight}
      ownerPageId={scope.sourcePageId}
      panelKind={componentPanelTaskKind(opened.contribution.componentId, opened.contribution.contributionId)}
      open={active && componentPanelOpen}
      onMinimize={() => setComponentPanelOpen(false)}
      onClose={() => { openGeneration.current += 1; void window.electronAPI.closeComponentPage(opened.instanceId).catch(() => undefined); setComponentPanelOpen(false); setOpened(null); }}
    />}
    {opened && opened.contribution.type !== 'component.sidePanel' && <aside aria-label={opened.contribution.title} style={{ width }} className="fixed bottom-3 right-3 top-14 z-[210] rounded-xl border border-slate-200 bg-white shadow-2xl"><header className="absolute inset-x-0 top-0 z-10 flex h-10 items-center justify-end border-b border-slate-200 bg-white px-2"><button type="button" aria-label={t("ui.close.plugin.panel.28a4de")} onClick={() => { openGeneration.current += 1; void window.electronAPI.closeComponentPage(opened.instanceId).catch(() => undefined); setOpened(null); }} className="rounded px-2 py-1 text-xs">{t("common.close")}</button></header><div ref={panelRef} data-component-view-host className="absolute inset-x-0 bottom-10 top-10"/><footer className="absolute inset-x-0 bottom-0 z-10 flex h-10 items-center border-t border-slate-200 bg-white px-3"><input aria-label={t("ui.resize.plugin.panel.93bd04")} type="range" min="280" max="640" value={width} onChange={event => setWidth(Number(event.target.value))} className="w-28"/></footer></aside>}
    {commandsOpen && <div role="dialog" aria-modal="true" aria-label={t("ui.plugin.commands.c5f868")} className="fixed inset-0 z-[430] flex items-start justify-center bg-slate-950/35 pt-[12vh]" onMouseDown={closeCommands}><div className="w-full max-w-xl rounded-xl bg-white p-3 shadow-2xl" onMouseDown={event => event.stopPropagation()}><input autoFocus aria-label={t("ui.search.plugin.commands.bfa041")} aria-controls="component-command-options" aria-activedescendant={resolvedCommandIndex >= 0 ? `component-command-${resolvedCommandIndex}` : undefined} value={query} onChange={event => { setQuery(event.target.value); setActiveCommandIndex(0); }} onKeyDown={event => { if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); setActiveCommandIndex(current => nextCommandIndex(current, filtered.length, event.key)); } else if (event.key === 'Enter' && filtered[resolvedCommandIndex]) { event.preventDefault(); void open(filtered[resolvedCommandIndex]); } else if (event.key === 'Escape') { event.preventDefault(); closeCommands(); } }} placeholder={t("ui.search.commands.888c64")} className="w-full rounded-lg border border-slate-300 px-3 py-2"/><div id="component-command-options" role="listbox" className="mt-2 max-h-80 overflow-auto">{filtered.map((item, index) => <button id={`component-command-${index}`} role="option" aria-selected={index === resolvedCommandIndex} key={`${item.componentId}:${item.contributionId}`} className={`block w-full rounded-lg px-3 py-2 text-left hover:bg-blue-50 focus:bg-blue-50 ${index === resolvedCommandIndex ? 'bg-blue-50' : ''}`} onMouseEnter={() => setActiveCommandIndex(index)} onClick={() => void open(item)}>{item.label}</button>)}{!filtered.length && <p className="p-3 text-sm text-slate-400">{t("ui.no.matching.commands.e0ea16")}</p>}</div><button type="button" className="mt-2 rounded px-3 py-1 text-sm" onClick={closeCommands}>{t("common.close")}</button></div></div>}</>;
};
