#define _GNU_SOURCE
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/wait.h>
#include <unistd.h>
#ifndef O_DIRECTORY
#define O_DIRECTORY 0
#endif
#ifdef __APPLE__
#define RENAME_EXCL 0x00000004
extern int renamex_np(const char *, const char *, unsigned int);
#endif

typedef struct { uint32_t h[8]; uint64_t bits; unsigned char block[64]; size_t used; } sha256_ctx;
static const uint32_t sha_k[64] = { 0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2 };
static uint32_t rr(uint32_t v,unsigned n){return(v>>n)|(v<<(32-n));}
static void sha_block(sha256_ctx*c,const unsigned char*p){uint32_t w[64],a,b,d,e,f,g,h,i,t1,t2,cc;for(i=0;i<16;i++)w[i]=((uint32_t)p[i*4]<<24)|((uint32_t)p[i*4+1]<<16)|((uint32_t)p[i*4+2]<<8)|p[i*4+3];for(i=16;i<64;i++){uint32_t x=w[i-15],y=w[i-2];w[i]=(rr(y,17)^rr(y,19)^(y>>10))+w[i-7]+(rr(x,7)^rr(x,18)^(x>>3))+w[i-16];}a=c->h[0];b=c->h[1];cc=c->h[2];d=c->h[3];e=c->h[4];f=c->h[5];g=c->h[6];h=c->h[7];for(i=0;i<64;i++){t1=h+(rr(e,6)^rr(e,11)^rr(e,25))+((e&f)^((~e)&g))+sha_k[i]+w[i];t2=(rr(a,2)^rr(a,13)^rr(a,22))+((a&b)^(a&cc)^(b&cc));h=g;g=f;f=e;e=d+t1;d=cc;cc=b;b=a;a=t1+t2;}c->h[0]+=a;c->h[1]+=b;c->h[2]+=cc;c->h[3]+=d;c->h[4]+=e;c->h[5]+=f;c->h[6]+=g;c->h[7]+=h;}
static void sha_init(sha256_ctx*c){static const uint32_t v[8]={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19};memcpy(c->h,v,sizeof(v));c->bits=0;c->used=0;}
static void sha_update(sha256_ctx*c,const unsigned char*p,size_t n){c->bits+=(uint64_t)n*8;while(n){size_t take=64-c->used;if(take>n)take=n;memcpy(c->block+c->used,p,take);c->used+=take;p+=take;n-=take;if(c->used==64){sha_block(c,c->block);c->used=0;}}}
static void sha_final(sha256_ctx*c,char out[65]){size_t i;c->block[c->used++]=0x80;if(c->used>56){while(c->used<64)c->block[c->used++]=0;sha_block(c,c->block);c->used=0;}while(c->used<56)c->block[c->used++]=0;for(i=0;i<8;i++)c->block[63-i]=(unsigned char)(c->bits>>(i*8));sha_block(c,c->block);for(i=0;i<8;i++)sprintf(out+i*8,"%08x",c->h[i]);out[64]=0;}

static void json(int ok,const char*code,const char*message,const char*extra){printf("{\"success\":%s,\"code\":\"%s\",\"error\":\"%s\"%s}\n",ok?"true":"false",code?code:"",message?message:"",extra?extra:"");}
static const char*map_code(int e){if(e==EINVAL)return"EINVAL";if(e==EEXIST||e==ENOTEMPTY)return"EEXIST";if(e==EXDEV)return"EXDEV";if(e==ENOENT)return"ENOENT";if(e==ENAMETOOLONG)return"ENAMETOOLONG";if(e==EACCES||e==EPERM)return"EACCES";return"FILE_PUBLICATION_FAILED";}
static const char*arg(int argc,char**argv,const char*name){int i;for(i=2;i+1<argc;i+=2)if(!strcmp(argv[i],name))return argv[i+1];return NULL;}
static int valid(const char*p){return p&&p[0]=='/';}
static int move_excl(const char*s,const char*t){
#ifdef __APPLE__
return renamex_np(s,t,RENAME_EXCL);
#else
return syscall(SYS_renameat2,AT_FDCWD,s,AT_FDCWD,t,1);
#endif
}
static void identity(const struct stat*s,char out[96]){snprintf(out,96,"%llu:%llu",(unsigned long long)s->st_dev,(unsigned long long)s->st_ino);}
static int verify_identity(int fd,const char*expected){struct stat s;char actual[96];if(fstat(fd,&s))return-1;identity(&s,actual);return strcmp(actual,expected)?1:0;}
static int verify_file(int fd,const char*hash,long long size){struct stat s;unsigned char buf[1024*1024];ssize_t n;sha256_ctx c;char actual[65];if(fstat(fd,&s))return-1;if(!S_ISREG(s.st_mode)||s.st_size!=size)return 1;if(lseek(fd,0,SEEK_SET)<0)return-1;sha_init(&c);while((n=read(fd,buf,sizeof(buf)))>0)sha_update(&c,buf,(size_t)n);if(n<0)return-1;sha_final(&c,actual);return strcasecmp(actual,hash)?1:0;}
static int same_path(int fd,const char*p){struct stat a,b;if(fstat(fd,&a)||lstat(p,&b))return-1;return(a.st_dev==b.st_dev&&a.st_ino==b.st_ino)?0:1;}
static const char*path_basename(const char*p){const char*s=strrchr(p,'/');return s?s+1:p;}
static int same_at(int fd,int dirfd,const char*name){struct stat a,b;if(fstat(fd,&a)||fstatat(dirfd,name,&b,AT_SYMLINK_NOFOLLOW))return-1;return(a.st_dev==b.st_dev&&a.st_ino==b.st_ino)?0:1;}
static int make_private_quarantine(const char*p,char**directory,char**recovery,int*dirfd){const char*slash=strrchr(p,'/'),*base=path_basename(p);size_t parent_len,template_len,recovery_len;char*d,*q;if(!slash||!*base){errno=EINVAL;return-1;}parent_len=slash==p?1:(size_t)(slash-p);template_len=parent_len+40;d=(char*)malloc(template_len);if(!d)return-1;snprintf(d,template_len,"%.*s%s.photoflow-quarantine-XXXXXX",(int)parent_len,p,parent_len==1?"":"/");if(!mkdtemp(d)){free(d);return-1;}if(chmod(d,0700)){int saved=errno;rmdir(d);free(d);errno=saved;return-1;}*dirfd=open(d,O_RDONLY|O_CLOEXEC|O_DIRECTORY);if(*dirfd<0){int saved=errno;rmdir(d);free(d);errno=saved;return-1;}recovery_len=strlen(d)+strlen(base)+2;q=(char*)malloc(recovery_len);if(!q){int saved=errno;close(*dirfd);rmdir(d);free(d);errno=saved;return-1;}snprintf(q,recovery_len,"%s/%s",d,base);*directory=d;*recovery=q;return 0;}
static int same_version(const struct stat*a,const struct stat*b){
#ifdef __APPLE__
return a->st_dev==b->st_dev&&a->st_ino==b->st_ino&&a->st_size==b->st_size&&a->st_mtimespec.tv_sec==b->st_mtimespec.tv_sec&&a->st_mtimespec.tv_nsec==b->st_mtimespec.tv_nsec&&a->st_ctimespec.tv_sec==b->st_ctimespec.tv_sec&&a->st_ctimespec.tv_nsec==b->st_ctimespec.tv_nsec;
#else
return a->st_dev==b->st_dev&&a->st_ino==b->st_ino&&a->st_size==b->st_size&&a->st_mtim.tv_sec==b->st_mtim.tv_sec&&a->st_mtim.tv_nsec==b->st_mtim.tv_nsec&&a->st_ctim.tv_sec==b->st_ctim.tv_sec&&a->st_ctim.tv_nsec==b->st_ctim.tv_nsec;
#endif
}
static int fsync_parent(const char*p){char*d=strdup(p),*slash;int fd,r,saved;if(!d)return-1;slash=strrchr(d,'/');if(!slash){free(d);errno=EINVAL;return-1;}if(slash==d)slash[1]=0;else*slash=0;
#ifdef PHOTOFLOW_TEST_FAULTS
{const char*watched=getenv("PHOTOFLOW_TEST_FAIL_FSYNC_PARENT");if(watched&&!strcmp(watched,p)){free(d);errno=EIO;return-1;}}
#endif
fd=open(d,O_RDONLY|O_CLOEXEC|O_DIRECTORY);free(d);if(fd<0)return-1;r=fsync(fd);saved=errno;close(fd);errno=saved;return r;}
static int fsync_rename_parents(const char*s,const char*t){if(fsync_parent(s))return-1;if(strcmp(s,t)&&fsync_parent(t))return-1;return 0;}
static int stable_file(int fd,const char*hash,long long size){struct stat before,after;int r;if(fstat(fd,&before))return-1;r=verify_file(fd,hash,size);if(r)return r;if(fsync(fd))return-1;if(fstat(fd,&after))return-1;return same_version(&before,&after)?0:1;}
#ifdef PHOTOFLOW_TEST_FAULTS
static void test_replace_after_verify(const char*p){const char*watched=getenv("PHOTOFLOW_TEST_REPLACE_AFTER_VERIFY");const char*replacement=getenv("PHOTOFLOW_TEST_REPLACEMENT_PATH");const char*retained=getenv("PHOTOFLOW_TEST_RETAINED_PATH");if(watched&&replacement&&retained&&!strcmp(watched,p)){if(rename(p,retained)||rename(replacement,p)){fprintf(stderr,"test replacement injection failed: %s\n",strerror(errno));exit(90);}}}
static void test_batch_occupy_original(const char*p){const char*watched=getenv("PHOTOFLOW_TEST_BATCH_DELETE_OCCUPY_ORIGINAL");if(watched&&!strcmp(watched,p)){int fd=open(p,O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC,0600);if(fd<0){fprintf(stderr,"test batch occupation injection failed: %s\n",strerror(errno));exit(91);}close(fd);}}
static void test_single_occupy_original(const char*p){const char*watched=getenv("PHOTOFLOW_TEST_SINGLE_DELETE_OCCUPY_ORIGINAL");if(watched&&!strcmp(watched,p)){int fd=open(p,O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC,0600);if(fd<0){fprintf(stderr,"test single occupation injection failed: %s\n",strerror(errno));exit(92);}close(fd);}}
static int test_single_fail_unlink(const char*p){const char*watched=getenv("PHOTOFLOW_TEST_SINGLE_DELETE_FAIL_UNLINK");if(watched&&!strcmp(watched,p)){errno=EACCES;return 1;}return 0;}
static int test_batch_fail_unlink(const char*p){const char*watched=getenv("PHOTOFLOW_TEST_BATCH_DELETE_FAIL_UNLINK");if(watched&&!strcmp(watched,p)){errno=EACCES;return 1;}return 0;}
static void test_write_after_quarantine(const char*q,const char*p){const char*watched=getenv("PHOTOFLOW_TEST_WRITE_AFTER_QUARANTINE");if(watched&&!strcmp(watched,p)){int fd=open(q,O_WRONLY|O_TRUNC|O_CLOEXEC);if(fd<0||write(fd,"changed-after-verify",20)!=20){fprintf(stderr,"test quarantine write injection failed: %s\n",strerror(errno));exit(93);}close(fd);}}
static int test_fail_rmdir_after_unlink(const char*p){const char*watched=getenv("PHOTOFLOW_TEST_FAIL_RMDIR_AFTER_UNLINK");if(watched&&!strcmp(watched,p)){errno=EIO;return 1;}return 0;}
static int test_fail_final_parent_fsync(const char*p){const char*watched=getenv("PHOTOFLOW_TEST_FAIL_FINAL_PARENT_FSYNC");if(watched&&!strcmp(watched,p)){errno=EIO;return 1;}return 0;}
static ssize_t test_manifest_read(int fd,void*buffer,size_t count,const char*p,size_t offset,long long expected){const char*fail=getenv("PHOTOFLOW_TEST_FAIL_MANIFEST_READ"),*short_eof=getenv("PHOTOFLOW_TEST_SHORT_MANIFEST_READ");if(fail&&!strcmp(fail,p)){errno=EIO;return-1;}if(short_eof&&!strcmp(short_eof,p)&&offset>=(size_t)(expected/2))return 0;if(count>7)count=7;return read(fd,buffer,count);}
static void test_mutate_manifest_after_read(const char*p){const char*watched=getenv("PHOTOFLOW_TEST_MUTATE_MANIFEST_AFTER_READ"),*replacement=getenv("PHOTOFLOW_TEST_MANIFEST_REPLACEMENT");pid_t child;int status;if(!watched||!replacement||strcmp(watched,p))return;child=fork();if(child==0){char buffer[4096];ssize_t n;int source=open(replacement,O_RDONLY|O_CLOEXEC),target=open(p,O_WRONLY|O_TRUNC|O_CLOEXEC);if(source<0||target<0)_exit(94);while((n=read(source,buffer,sizeof(buffer)))>0){ssize_t offset=0;while(offset<n){ssize_t written=write(target,buffer+offset,(size_t)(n-offset));if(written<0&&errno==EINTR)continue;if(written<=0)_exit(94);offset+=written;}}if(n<0)_exit(94);close(source);close(target);_exit(0);}if(child<0||waitpid(child,&status,0)<0||!WIFEXITED(status)||WEXITSTATUS(status)!=0){fprintf(stderr,"test manifest mutation failed: %s\n",strerror(errno));exit(94);}}
#else
static void test_replace_after_verify(const char*p){(void)p;}
static void test_batch_occupy_original(const char*p){(void)p;}
static void test_single_occupy_original(const char*p){(void)p;}
static int test_single_fail_unlink(const char*p){(void)p;return 0;}
static int test_batch_fail_unlink(const char*p){(void)p;return 0;}
static void test_write_after_quarantine(const char*q,const char*p){(void)q;(void)p;}
static int test_fail_rmdir_after_unlink(const char*p){(void)p;return 0;}
static int test_fail_final_parent_fsync(const char*p){(void)p;return 0;}
static ssize_t test_manifest_read(int fd,void*buffer,size_t count,const char*p,size_t offset,long long expected){(void)p;(void)offset;(void)expected;return read(fd,buffer,count);}
static void test_mutate_manifest_after_read(const char*p){(void)p;}
#endif
static char*last_recovery=NULL;
static int last_deleted=0;
static int last_original_missing=0;
static void record_recovery(const char*q,const char*p){free(last_recovery);last_recovery=strdup(q);last_original_missing=access(p,F_OK)!=0;}
static int quarantine_delete(int fd,const char*p,const char*hash,long long size){
 char*d=NULL,*q=NULL;const char*base=path_basename(p);int dirfd=-1,r,saved,unlink_flags=0;struct stat held;
 free(last_recovery);last_recovery=NULL;last_deleted=0;last_original_missing=0;
 if(make_private_quarantine(p,&d,&q,&dirfd))return-1;
 if(move_excl(p,q)){saved=errno;close(dirfd);rmdir(d);free(q);free(d);errno=saved;return-1;}
 if(fsync(dirfd)||fsync_parent(p)){saved=errno;record_recovery(q,p);close(dirfd);free(q);free(d);errno=saved;return-1;}
 test_single_occupy_original(p);test_batch_occupy_original(p);
 if(access(p,F_OK)==0){record_recovery(q,p);close(dirfd);free(q);free(d);errno=ESTALE;return 1;}
 r=same_at(fd,dirfd,base);if(r){saved=r>0?ESTALE:errno;record_recovery(q,p);close(dirfd);free(q);free(d);errno=saved;return r>0?1:-1;}
 test_write_after_quarantine(q,p);
 if(hash&&(r=stable_file(fd,hash,size))!=0){saved=r>0?ESTALE:errno;record_recovery(q,p);close(dirfd);free(q);free(d);errno=saved;return r>0?1:-1;}
 if(fstat(fd,&held)){saved=errno;record_recovery(q,p);close(dirfd);free(q);free(d);errno=saved;return-1;}
 if(S_ISDIR(held.st_mode))unlink_flags=AT_REMOVEDIR;
 r=same_at(fd,dirfd,base);if(r){saved=r>0?ESTALE:errno;record_recovery(q,p);close(dirfd);free(q);free(d);errno=saved;return r>0?1:-1;}
 if(test_single_fail_unlink(p)||test_batch_fail_unlink(p)||unlinkat(dirfd,base,unlink_flags)){saved=errno;record_recovery(q,p);close(dirfd);free(q);free(d);errno=saved;return-1;}
 last_deleted=1;free(last_recovery);last_recovery=NULL;
 if(fsync(dirfd)){saved=errno;last_deleted=1;close(dirfd);rmdir(d);free(q);free(d);errno=saved;return-1;}
 close(dirfd);if(test_fail_rmdir_after_unlink(p)||rmdir(d)){saved=errno;free(q);free(d);errno=saved;return-1;}
 if(test_fail_final_parent_fsync(p)||fsync_parent(p)){saved=errno;free(q);free(d);errno=saved;return-1;}
 free(q);free(d);return 0;
}
static int b64v(int c){if(c>='A'&&c<='Z')return c-'A';if(c>='a'&&c<='z')return c-'a'+26;if(c>='0'&&c<='9')return c-'0'+52;if(c=='+')return 62;if(c=='/')return 63;return-1;}
static char*b64decode(const char*text){size_t n=strlen(text),i,o=0;char*out;if(!n||n%4)return NULL;out=(char*)malloc(n/4*3+1);if(!out)return NULL;for(i=0;i<n;i+=4){int a=b64v(text[i]),b=b64v(text[i+1]),c=text[i+2]=='='?-2:b64v(text[i+2]),d=text[i+3]=='='?-2:b64v(text[i+3]);if(a<0||b<0||c==-1||d==-1||(c==-2&&d!=-2)){free(out);return NULL;}out[o++]=(char)((a<<2)|(b>>4));if(c>=0){out[o++]=(char)((b<<4)|(c>>2));if(d>=0)out[o++]=(char)((c<<6)|d);}if((c==-2||d==-2)&&i+4!=n){free(out);return NULL;}}out[o]=0;if(strlen(out)!=o){free(out);return NULL;}return out;}
static char*b64encode(const unsigned char*data,size_t n){static const char t[]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";size_t i,o=0;char*out=(char*)malloc(((n+2)/3)*4+1);if(!out)return NULL;for(i=0;i<n;i+=3){unsigned v=(unsigned)data[i]<<16;if(i+1<n)v|=(unsigned)data[i+1]<<8;if(i+2<n)v|=data[i+2];out[o++]=t[(v>>18)&63];out[o++]=t[(v>>12)&63];out[o++]=i+1<n?t[(v>>6)&63]:'=';out[o++]=i+2<n?t[v&63]:'=';}out[o]=0;return out;}
static int recovery_error(int e,const char*code,const char*message){(void)e;if(last_recovery){char*encoded=b64encode((const unsigned char*)last_recovery,strlen(last_recovery));if(encoded){size_t n=strlen(encoded)+80;char*x=(char*)malloc(n);if(x){snprintf(x,n,",\"recoveryPathBase64\":\"%s\",\"originalMissing\":%s",encoded,last_original_missing?"true":"false");json(0,code,message,x);free(x);free(encoded);return 1;}free(encoded);}}json(0,code,message,last_deleted?",\"deleted\":true,\"outcomeUnknown\":true,\"cleanupWarning\":true,\"phase\":\"post-unlink-cleanup\"":NULL);return 1;}
static int fail_errno(void){int e=errno;return recovery_error(e,map_code(e),strerror(e));}
static int conflict(const char*m){return recovery_error(ESTALE,"PUBLISH_OWNERSHIP_CONFLICT",m);}
static int committed_error(int e,const char*m,const char*id){const char*code=e==ESTALE?"PUBLISH_OWNERSHIP_CONFLICT":map_code(e);char*encoded=NULL;size_t n=strlen(m)+(id?strlen(id):0)+(last_recovery?strlen(last_recovery)*2:0)+384;char*x=(char*)malloc(n);if(!x){json(0,code,m,",\"published\":true,\"outcomeUnknown\":true");return 1;}if(last_deleted)snprintf(x,n,",\"published\":true,\"outcomeUnknown\":true,\"deleted\":true,\"cleanupWarning\":true,\"phase\":\"post-unlink-cleanup\"%s%s%s",id?",\"identity\":\"":"",id?id:"",id?"\"":"");else{if(last_recovery)encoded=b64encode((const unsigned char*)last_recovery,strlen(last_recovery));if(encoded)snprintf(x,n,",\"published\":true,\"outcomeUnknown\":true%s%s%s,\"recoveryPathBase64\":\"%s\",\"originalMissing\":%s",id?",\"identity\":\"":"",id?id:"",id?"\"":"",encoded,last_original_missing?"true":"false");else snprintf(x,n,",\"published\":true,\"outcomeUnknown\":true%s%s%s",id?",\"identity\":\"":"",id?id:"",id?"\"":"");}json(0,code,m,x);free(encoded);free(x);return 1;}
static int split_fields(char*line,char**fields,int count){int i;size_t n=strlen(line);while(n&&(line[n-1]=='\n'||line[n-1]=='\r'))line[--n]=0;fields[0]=line;for(i=1;i<count;i++){fields[i]=strchr(fields[i-1],'\t');if(!fields[i])return-1;*fields[i]++=0;}return strchr(fields[count-1],'\t')?-1:0;}
static int batch_inspect(const char*manifest){FILE*f;char*line=NULL;size_t cap=0;ssize_t len;int expected=0,first=1;if(!valid(manifest)){json(0,"EINVAL","absolute manifest required",NULL);return 1;}f=fopen(manifest,"r");if(!f)return fail_errno();printf("{\"success\":true,\"results\":[");while((len=getline(&line,&cap,f))>=0){char*parts[2],*p;long index;struct stat st;char id[96];if(split_fields(line,parts,2)){free(line);fclose(f);json(0,"EINVAL","invalid inspection manifest",NULL);return 1;}index=strtol(parts[0],NULL,10);p=b64decode(parts[1]);if(index!=expected++||!p||!valid(p)){free(p);free(line);fclose(f);json(0,"EINVAL","invalid inspection item",NULL);return 1;}if(!first)printf(",");first=0;if(lstat(p,&st))printf("{\"index\":%ld,\"success\":false,\"code\":\"%s\",\"error\":\"path unavailable\"}",index,map_code(errno));else{identity(&st,id);printf("{\"index\":%ld,\"success\":true,\"identity\":\"%s\",\"directory\":%s}",index,id,S_ISDIR(st.st_mode)?"true":"false");}free(p);if(expected>4096){free(line);fclose(f);json(0,"EINVAL","inspection batch too large",NULL);return 1;}}free(line);fclose(f);printf("]}\n");return 0;}
static int batch_move(const char*manifest){FILE*f;char*line=NULL;size_t cap=0;ssize_t len;int expected=0,first=1,stop=0;if(!valid(manifest)){json(0,"EINVAL","absolute manifest required",NULL);return 1;}f=fopen(manifest,"r");if(!f)return fail_errno();printf("{\"success\":true,\"results\":[");while(!stop&&(len=getline(&line,&cap,f))>=0){char*parts[4],*s,*t,*wanted;long index;int fd,r,saved;struct stat st;char id[96];if(split_fields(line,parts,4)){free(line);fclose(f);json(0,"EINVAL","invalid publication manifest",NULL);return 1;}index=strtol(parts[0],NULL,10);s=b64decode(parts[1]);t=b64decode(parts[2]);wanted=b64decode(parts[3]);if(index!=expected++||!s||!t||!wanted||!valid(s)||!valid(t)||!strcmp(s,t)){free(s);free(t);free(wanted);free(line);fclose(f);json(0,"EINVAL","invalid publication item",NULL);return 1;}if(!first)printf(",");first=0;fd=open(s,O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(fd<0){printf("{\"index\":%ld,\"success\":false,\"code\":\"%s\",\"error\":\"source unavailable\"}",index,map_code(errno));stop=1;}else if((r=verify_identity(fd,wanted))!=0){printf("{\"index\":%ld,\"success\":false,\"code\":\"PUBLISH_OWNERSHIP_CONFLICT\",\"error\":\"source identity changed\"}",index);stop=1;close(fd);}else{fstat(fd,&st);identity(&st,id);if(move_excl(s,t)){printf("{\"index\":%ld,\"success\":false,\"code\":\"%s\",\"error\":\"publication failed\"}",index,map_code(errno));stop=1;}else if(fsync_rename_parents(s,t)){saved=errno;printf("{\"index\":%ld,\"success\":false,\"code\":\"%s\",\"error\":\"publication durability unknown\",\"published\":true,\"outcomeUnknown\":true,\"identity\":\"%s\"}",index,map_code(saved),id);stop=1;}else if(same_path(fd,t)){printf("{\"index\":%ld,\"success\":false,\"code\":\"PUBLISH_OWNERSHIP_CONFLICT\",\"error\":\"published target identity changed\",\"published\":true,\"outcomeUnknown\":true,\"identity\":\"%s\"}",index,id);stop=1;}else printf("{\"index\":%ld,\"success\":true,\"strategy\":\"posix-batch-rename-no-replace\",\"identity\":\"%s\"}",index,id);close(fd);}free(s);free(t);free(wanted);if(expected>2048){free(line);fclose(f);json(0,"EINVAL","publication batch too large",NULL);return 1;}}free(line);fclose(f);printf("]}\n");return 0;}
static int batch_delete(const char*manifest){
 FILE*f;char*line=NULL;size_t cap=0;ssize_t len;int expected=0,first=1;
 if(!valid(manifest)){json(0,"EINVAL","absolute manifest required",NULL);return 1;}
 f=fopen(manifest,"r");if(!f)return fail_errno();printf("{\"success\":true,\"results\":[");
 while((len=getline(&line,&cap,f))>=0){
  char*parts[3],*p,*wanted,*encoded=NULL;long index;int fd,r,saved=0;
  if(split_fields(line,parts,3)){free(line);fclose(f);json(0,"EINVAL","invalid cleanup manifest",NULL);return 1;}
  index=strtol(parts[0],NULL,10);p=b64decode(parts[1]);wanted=b64decode(parts[2]);
  if(index!=expected++||!p||!wanted||!valid(p)){free(p);free(wanted);free(line);fclose(f);json(0,"EINVAL","invalid cleanup item",NULL);return 1;}
  if(!first)printf(",");first=0;
  fd=open(p,O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(fd<0){printf("{\"index\":%ld,\"success\":false,\"code\":\"%s\",\"error\":\"cleanup source unavailable\"}",index,map_code(errno));}
  else if((r=verify_identity(fd,wanted))!=0){printf("{\"index\":%ld,\"success\":false,\"code\":\"PUBLISH_OWNERSHIP_CONFLICT\",\"error\":\"cleanup identity changed\"}",index);close(fd);}
  else{free(last_recovery);last_recovery=NULL;r=quarantine_delete(fd,p,NULL,0);saved=errno;close(fd);if(!r)printf("{\"index\":%ld,\"success\":true,\"deleted\":true}",index);else if(last_recovery){encoded=b64encode((const unsigned char*)last_recovery,strlen(last_recovery));printf("{\"index\":%ld,\"success\":false,\"code\":\"%s\",\"error\":\"private quarantine retained\",\"recoveryPathBase64\":\"%s\",\"originalMissing\":%s}",index,r>0?"PUBLISH_OWNERSHIP_CONFLICT":map_code(saved),encoded?encoded:"",last_original_missing?"true":"false");}else printf("{\"index\":%ld,\"success\":false,\"code\":\"%s\",\"error\":\"private quarantine cleanup failed\"%s}",index,r>0?"PUBLISH_OWNERSHIP_CONFLICT":map_code(saved),last_deleted?",\"deleted\":true,\"outcomeUnknown\":true,\"cleanupWarning\":true,\"phase\":\"post-unlink-cleanup\"":"");}
  free(encoded);free(p);free(wanted);if(expected>2048){free(line);fclose(f);json(0,"EINVAL","cleanup batch too large",NULL);return 1;}
 }
 free(line);fclose(f);printf("]}\n");return 0;
}
static const char*find_dir_identity(char**paths,char**ids,int count,const char*p){int i;for(i=0;i<count;i++)if(!strcmp(paths[i],p))return ids[i];return NULL;}
static int hex_sha256(const char*s);
static char*read_bound_manifest(const char*p,const char*hash,long long size,size_t*length){int fd,saved;struct stat st;char*bytes,extra;size_t offset=0;ssize_t n;sha256_ctx digest;char actual[65];if(!valid(p)||!hex_sha256(hash)||size<0||size>512*1024){errno=EINVAL;return NULL;}fd=open(p,O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(fd<0)return NULL;if(fstat(fd,&st)){saved=errno;close(fd);errno=saved;return NULL;}if(!S_ISREG(st.st_mode)||st.st_nlink!=1||st.st_uid!=geteuid()||(st.st_mode&0022)||st.st_size!=size){close(fd);errno=EPERM;return NULL;}bytes=(char*)malloc((size_t)size+1);if(!bytes){close(fd);errno=ENOMEM;return NULL;}while(offset<(size_t)size){n=test_manifest_read(fd,bytes+offset,(size_t)size-offset,p,offset,size);if(n<0&&errno==EINTR)continue;if(n<=0){saved=n<0?errno:EIO;free(bytes);close(fd);errno=saved;return NULL;}offset+=(size_t)n;}for(;;){n=test_manifest_read(fd,&extra,1,p,offset,size);if(n<0&&errno==EINTR)continue;break;}if(n!=0){saved=n<0?errno:EOVERFLOW;free(bytes);close(fd);errno=saved;return NULL;}if(fstat(fd,&st)){saved=errno;free(bytes);close(fd);errno=saved;return NULL;}if(!S_ISREG(st.st_mode)||st.st_nlink!=1||st.st_uid!=geteuid()||(st.st_mode&0022)||st.st_size!=size){free(bytes);close(fd);errno=EPERM;return NULL;}close(fd);bytes[size]=0;if(memchr(bytes,0,(size_t)size)){free(bytes);errno=EINVAL;return NULL;}sha_init(&digest);sha_update(&digest,(const unsigned char*)bytes,(size_t)size);sha_final(&digest,actual);if(strcasecmp(actual,hash)){free(bytes);errno=ESTALE;return NULL;}test_mutate_manifest_after_read(p);*length=(size_t)size;return bytes;}
static int canonical_manifest_path(const char*p){const char*s,*end;size_t n;if(!valid(p)||p[0]!='/')return 0;n=strlen(p);if(n==1)return 1;if(p[n-1]=='/')return 0;for(s=p+1;*s;s=end+(*end=='/')){end=strchr(s,'/');if(!end)end=s+strlen(s);if(end==s||(end-s==1&&s[0]=='.')||(end-s==2&&s[0]=='.'&&s[1]=='.'))return 0;}return 1;}
static int path_under_root(const char*root,const char*p,int allow_root){size_t n=strlen(root);if(!canonical_manifest_path(root)||!canonical_manifest_path(p))return 0;if(!strcmp(root,p))return allow_root;if(!strcmp(root,"/"))return p[0]=='/'&&p[1];return !strncmp(root,p,n)&&p[n]=='/'&&p[n+1];}
struct destructive_target{long index;char*path;char*identity;long long size;char*hash;};
struct destructive_manifest{char*root;char**dir_paths;char**dir_ids;int dir_count;struct destructive_target*targets;int target_count;};
static void free_destructive_manifest(struct destructive_manifest*m){int i;if(!m)return;for(i=0;i<m->dir_count;i++){free(m->dir_paths[i]);free(m->dir_ids[i]);}if(m->targets)for(i=0;i<2048;i++){free(m->targets[i].path);free(m->targets[i].identity);free(m->targets[i].hash);}free(m->dir_paths);free(m->dir_ids);free(m->targets);free(m->root);memset(m,0,sizeof(*m));}
static int strict_long(const char*s,long*v){char*end,canonical[64];long n;if(!s||!*s)return 0;errno=0;n=strtol(s,&end,10);snprintf(canonical,sizeof(canonical),"%ld",n);if(errno||*end||strcmp(s,canonical))return 0;*v=n;return 1;}
static int strict_size(const char*s,long long*v){char*end,canonical[64];long long n;if(!s||!*s)return 0;errno=0;n=strtoll(s,&end,10);snprintf(canonical,sizeof(canonical),"%lld",n);if(errno||*end||n<0||strcmp(s,canonical))return 0;*v=n;return 1;}
static int hex_sha256(const char*s){int i;if(!s||strlen(s)!=64)return 0;for(i=0;i<64;i++)if(!((s[i]>='0'&&s[i]<='9')||(s[i]>='a'&&s[i]<='f')||(s[i]>='A'&&s[i]<='F')))return 0;return 1;}
static int complete_parent_chain(struct destructive_manifest*m,const char*p){char*parent=strdup(p),*slash;int ok=1;if(!parent)return 0;slash=strrchr(parent,'/');if(!slash){free(parent);return 0;}if(slash==parent)parent[1]=0;else*slash=0;for(;;){if(!find_dir_identity(m->dir_paths,m->dir_ids,m->dir_count,parent)){ok=0;break;}if(!strcmp(parent,"/"))break;slash=strrchr(parent,'/');if(!slash){ok=0;break;}if(slash==parent)parent[1]=0;else*slash=0;}free(parent);return ok;}
static int parse_destructive_manifest(char*bytes,size_t length,int directories_only,struct destructive_manifest*m){char*cursor=bytes,*end=bytes+length;int saw_target=0,ok=1,i;memset(m,0,sizeof(*m));m->dir_paths=(char**)calloc(2048,sizeof(char*));m->dir_ids=(char**)calloc(2048,sizeof(char*));m->targets=(struct destructive_target*)calloc(2048,sizeof(struct destructive_target));if(!m->dir_paths||!m->dir_ids||!m->targets){free_destructive_manifest(m);errno=ENOMEM;return-1;}while(ok&&cursor<end){char*line=cursor,*newline=(char*)memchr(cursor,'\n',(size_t)(end-cursor)),*parts[6];int fields;if(newline){*newline=0;cursor=newline+1;}else cursor=end;if(!*line){ok=0;break;}fields=line[0]=='F'?6:line[0]=='T'?4:line[0]=='D'?3:2;if(split_fields(line,parts,fields)){ok=0;break;}if(!strcmp(parts[0],"R")){if(m->root||saw_target){ok=0;break;}m->root=b64decode(parts[1]);ok=m->root&&!strcmp(m->root,"/");}else if(!strcmp(parts[0],"D")){char*p,*id;if(!m->root||saw_target||m->dir_count>=2048){ok=0;break;}p=b64decode(parts[1]);id=b64decode(parts[2]);ok=p&&id&&*id&&path_under_root(m->root,p,1);for(i=0;ok&&i<m->dir_count;i++)if(!strcmp(m->dir_paths[i],p))ok=0;if(ok){m->dir_paths[m->dir_count]=p;m->dir_ids[m->dir_count++]=id;}else{free(p);free(id);}}else if((!directories_only&&!strcmp(parts[0],"F"))||(directories_only&&!strcmp(parts[0],"T"))){struct destructive_target*t;long index;saw_target=1;if(m->target_count>=2048||!strict_long(parts[1],&index)||index!=m->target_count){ok=0;break;}t=&m->targets[m->target_count];t->index=index;t->path=b64decode(parts[2]);t->identity=b64decode(parts[3]);ok=t->path&&t->identity&&*t->identity&&m->root&&path_under_root(m->root,t->path,0);for(i=0;ok&&i<m->target_count;i++)if(!strcmp(m->targets[i].path,t->path))ok=0;if(ok&&!directories_only){ok=strict_size(parts[4],&t->size)&&hex_sha256(parts[5]);if(ok)t->hash=strdup(parts[5]);if(!t->hash)ok=0;}if(ok)m->target_count++;}else ok=0;}if(ok&&(!m->root||!saw_target||!find_dir_identity(m->dir_paths,m->dir_ids,m->dir_count,m->root)))ok=0;for(i=0;ok&&i<m->target_count;i++)ok=complete_parent_chain(m,m->targets[i].path);if(!ok){errno=EINVAL;free_destructive_manifest(m);return-1;}return 0;}
static int open_parent_chain(const char*root,const char*target,char**paths,char**ids,int dir_count,int*fds,int*fd_count,char**leaf){char*relative=NULL,*parents=NULL,*save=NULL,*segment,*current=NULL;size_t root_len=strlen(root);const char*wanted,*relative_start;int fd,r;if(root_len==1&&root[0]=='/'){if(target[0]!='/'||!target[1])return 1;relative_start=target+1;}else{if(strncmp(target,root,root_len)||target[root_len]!='/'||!target[root_len+1])return 1;relative_start=target+root_len+1;}wanted=find_dir_identity(paths,ids,dir_count,root);if(!wanted)return 1;fd=open(root,O_RDONLY|O_CLOEXEC|O_NOFOLLOW|O_DIRECTORY);if(fd<0)return-1;if((r=verify_identity(fd,wanted))!=0){close(fd);return r;}fds[(*fd_count)++]=fd;relative=strdup(relative_start);if(!relative)return-1;{char*slash=strrchr(relative,'/');if(slash){*slash=0;parents=relative;*leaf=strdup(slash+1);}else *leaf=strdup(relative);}if(!*leaf){free(relative);return-1;}current=strdup(root);if(!current){free(relative);free(*leaf);*leaf=NULL;return-1;}if(parents)for(segment=strtok_r(parents,"/",&save);segment;segment=strtok_r(NULL,"/",&save)){char*next;size_t n=strlen(current)+strlen(segment)+2;next=(char*)malloc(n);if(!next){free(current);free(relative);return-1;}if(!strcmp(current,"/"))snprintf(next,n,"/%s",segment);else snprintf(next,n,"%s/%s",current,segment);free(current);current=next;wanted=find_dir_identity(paths,ids,dir_count,current);if(!wanted){free(current);free(relative);return 1;}fd=openat(fds[*fd_count-1],segment,O_RDONLY|O_CLOEXEC|O_NOFOLLOW|O_DIRECTORY);if(fd<0){free(current);free(relative);return-1;}if((r=verify_identity(fd,wanted))!=0){close(fd);free(current);free(relative);return r;}fds[(*fd_count)++]=fd;if(*fd_count>=256){free(current);free(relative);errno=ELOOP;return-1;}}free(current);free(relative);return 0;}
static int batch_compare_delete(const char*manifest,const char*manifest_hash,long long manifest_size){
 char*bytes;size_t length;int first=1,item;struct destructive_manifest parsed;
 if(!valid(manifest)){json(0,"EINVAL","absolute manifest required",NULL);return 1;}
 bytes=read_bound_manifest(manifest,manifest_hash,manifest_size,&length);if(!bytes)return fail_errno();if(parse_destructive_manifest(bytes,length,0,&parsed)){free(bytes);return fail_errno();}free(bytes);printf("{\"success\":true,\"results\":[");
 for(item=0;item<parsed.target_count;item++){
  struct destructive_target*t=&parsed.targets[item];char*leaf=NULL;int fd=-1,r,saved=0,fds[256],fd_count=0,i;
  if(!first)printf(",");first=0;
  r=open_parent_chain(parsed.root,t->path,parsed.dir_paths,parsed.dir_ids,parsed.dir_count,fds,&fd_count,&leaf);if(r)printf("{\"index\":%ld,\"success\":false,\"deleted\":false,\"code\":\"%s\",\"error\":\"cleanup parent chain changed\"}",t->index,r>0?"PUBLISH_OWNERSHIP_CONFLICT":map_code(errno));
  else if((fd=openat(fds[fd_count-1],leaf,O_RDONLY|O_CLOEXEC|O_NOFOLLOW))<0)printf("{\"index\":%ld,\"success\":false,\"deleted\":false,\"code\":\"%s\",\"error\":\"cleanup source unavailable\"}",t->index,map_code(errno));
  else if(((r=verify_identity(fd,t->identity))!=0)||((r=verify_file(fd,t->hash,t->size))!=0)){saved=errno;printf("{\"index\":%ld,\"success\":false,\"deleted\":false,\"code\":\"%s\",\"error\":\"cleanup identity or digest changed\"}",t->index,r>0?"PUBLISH_OWNERSHIP_CONFLICT":map_code(saved));close(fd);}
  else{r=same_at(fd,fds[fd_count-1],leaf);if(!r)r=stable_file(fd,t->hash,t->size);if(!r&&unlinkat(fds[fd_count-1],leaf,0))r=-1;saved=errno;close(fd);if(!r&&fsync(fds[fd_count-1])){r=-1;saved=errno;last_deleted=1;}if(!r)printf("{\"index\":%ld,\"success\":true,\"deleted\":true}",t->index);else if(last_deleted)printf("{\"index\":%ld,\"success\":false,\"deleted\":true,\"outcomeUnknown\":true,\"cleanupWarning\":true,\"phase\":\"post-unlink-cleanup\",\"code\":\"%s\"}",t->index,map_code(saved));else printf("{\"index\":%ld,\"success\":false,\"deleted\":false,\"code\":\"%s\",\"error\":\"cleanup stable identity changed\"}",t->index,r>0?"PUBLISH_OWNERSHIP_CONFLICT":map_code(saved));}
  for(i=0;i<fd_count;i++)close(fds[i]);free(leaf);last_deleted=0;
 }
 free_destructive_manifest(&parsed);printf("]}\n");return 0;
}
static int batch_delete_directories(const char*manifest,const char*manifest_hash,long long manifest_size){char*bytes;size_t length;int first=1,item;struct destructive_manifest parsed;if(!valid(manifest)){json(0,"EINVAL","absolute manifest required",NULL);return 1;}bytes=read_bound_manifest(manifest,manifest_hash,manifest_size,&length);if(!bytes)return fail_errno();if(parse_destructive_manifest(bytes,length,1,&parsed)){free(bytes);return fail_errno();}free(bytes);printf("{\"success\":true,\"results\":[");for(item=0;item<parsed.target_count;item++){struct destructive_target*t=&parsed.targets[item];char*leaf=NULL;int fds[256],fd_count=0,fd=-1,r=0,i,saved=0,deleted=0;if(!first)printf(",");first=0;r=open_parent_chain(parsed.root,t->path,parsed.dir_paths,parsed.dir_ids,parsed.dir_count,fds,&fd_count,&leaf);if(!r){fd=openat(fds[fd_count-1],leaf,O_RDONLY|O_CLOEXEC|O_NOFOLLOW|O_DIRECTORY);if(fd<0)r=-1;else if((r=verify_identity(fd,t->identity))==0){r=same_at(fd,fds[fd_count-1],leaf);if(!r){if(unlinkat(fds[fd_count-1],leaf,AT_REMOVEDIR))r=-1;else{deleted=1;if(fsync(fds[fd_count-1]))r=-1;}}}saved=errno;}if(fd>=0)close(fd);for(i=0;i<fd_count;i++)close(fds[i]);if(!r)printf("{\"index\":%ld,\"success\":true,\"deleted\":true}",t->index);else if(deleted)printf("{\"index\":%ld,\"success\":false,\"deleted\":true,\"outcomeUnknown\":true,\"cleanupWarning\":true,\"phase\":\"post-unlink-cleanup\",\"code\":\"%s\"}",t->index,map_code(saved));else printf("{\"index\":%ld,\"success\":false,\"deleted\":false,\"code\":\"%s\",\"error\":\"directory identity changed or is not empty\"}",t->index,r>0?"PUBLISH_OWNERSHIP_CONFLICT":map_code(saved));free(leaf);}free_destructive_manifest(&parsed);printf("]}\n");return 0;}

int main(int argc,char**argv){
 if(argc<2){json(0,"EINVAL","missing operation",NULL);return 1;}const char*op=argv[1];
 if(!strcmp(op,"move-no-replace-batch")){const char*m=arg(argc,argv,"--manifest");return batch_move(m);}
 if(!strcmp(op,"inspect-path-batch")){const char*m=arg(argc,argv,"--manifest");return batch_inspect(m);}
 if(!strcmp(op,"delete-paths-batch")){const char*m=arg(argc,argv,"--manifest");return batch_delete(m);}
 if(!strcmp(op,"compare-delete-files-batch")){const char*m=arg(argc,argv,"--manifest"),*h=arg(argc,argv,"--manifest-sha256"),*z=arg(argc,argv,"--manifest-size");return batch_compare_delete(m,h,z?atoll(z):-1);}
 if(!strcmp(op,"delete-directories-batch")){const char*m=arg(argc,argv,"--manifest"),*h=arg(argc,argv,"--manifest-sha256"),*z=arg(argc,argv,"--manifest-size");return batch_delete_directories(m,h,z?atoll(z):-1);}
 if(!strcmp(op,"move-no-replace")){const char*s=arg(argc,argv,"--source"),*t=arg(argc,argv,"--target");struct stat st;char id[96],extra[180];int fd,saved;if(!valid(s)||!valid(t)){json(0,"EINVAL","absolute paths required",NULL);return 1;}fd=open(s,O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(fd<0)return fail_errno();if(fstat(fd,&st)){close(fd);return fail_errno();}identity(&st,id);if(move_excl(s,t)){close(fd);return fail_errno();}if(fsync_rename_parents(s,t)){saved=errno;close(fd);return committed_error(saved,"publication rename completed but directory durability is unknown",id);}if(same_path(fd,t)){close(fd);return committed_error(ESTALE,"publication rename completed but target identity could not be confirmed",id);}close(fd);snprintf(extra,sizeof(extra),",\"strategy\":\"posix-rename-no-replace\",\"identity\":\"%s\"",id);json(1,"","",extra);return 0;}
 if(!strcmp(op,"inspect-path")){const char*p=arg(argc,argv,"--path");struct stat s;char id[96],extra[180];if(!valid(p)){json(0,"EINVAL","absolute path required",NULL);return 1;}if(lstat(p,&s))return fail_errno();identity(&s,id);snprintf(extra,sizeof(extra),",\"identity\":\"%s\",\"directory\":%s",id,S_ISDIR(s.st_mode)?"true":"false");json(1,"","",extra);return 0;}
 if(!strcmp(op,"compare-delete-file")){const char*p=arg(argc,argv,"--target"),*h=arg(argc,argv,"--sha256"),*id=arg(argc,argv,"--identity"),*z=arg(argc,argv,"--size");int fd,r;if(!valid(p)||!h||!id||!z){json(0,"EINVAL","invalid arguments",NULL);return 1;}fd=open(p,O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(fd<0)return fail_errno();r=verify_identity(fd,id);if(!r)r=verify_file(fd,h,atoll(z));if(!r)test_replace_after_verify(p);if(!r)r=quarantine_delete(fd,p,h,atoll(z));if(r){close(fd);return r>0?conflict("compensation target identity, digest, or stable version changed"):fail_errno();}close(fd);json(1,"","",",\"deleted\":true");return 0;}
 if(!strcmp(op,"commit-cross-volume-file")){const char*s=arg(argc,argv,"--source"),*st=arg(argc,argv,"--staged"),*t=arg(argc,argv,"--target"),*h=arg(argc,argv,"--sha256"),*id=arg(argc,argv,"--source-identity"),*z=arg(argc,argv,"--size");int sf,tf,r,saved;struct stat published;char published_id[96];if(!valid(s)||!valid(st)||!valid(t)||!h||!id||!z){json(0,"EINVAL","invalid arguments",NULL);return 1;}sf=open(s,O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(sf<0)return fail_errno();r=verify_identity(sf,id);if(r){close(sf);return r>0?conflict("source identity changed before publish"):fail_errno();}tf=open(st,O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(tf<0){close(sf);return fail_errno();}r=verify_file(tf,h,atoll(z));if(r){close(sf);close(tf);return r>0?conflict("staged digest changed before publish"):fail_errno();}if(fstat(tf,&published)){close(sf);close(tf);return fail_errno();}identity(&published,published_id);if(move_excl(st,t)){close(sf);close(tf);return fail_errno();}if(fsync_rename_parents(st,t)){saved=errno;close(sf);close(tf);return committed_error(saved,"target was published but directory durability is unknown",published_id);}r=same_path(tf,t);if(!r)r=stable_file(tf,h,atoll(z));if(r){saved=r>0?ESTALE:errno;close(sf);close(tf);return committed_error(saved,"published target identity, digest, or stable version changed",published_id);}r=stable_file(sf,h,atoll(z));if(!r)test_replace_after_verify(s);if(!r)r=quarantine_delete(sf,s,h,atoll(z));if(r){saved=r>0?ESTALE:errno;close(sf);close(tf);return committed_error(saved,"target is published but source cleanup requires recovery",published_id);}close(sf);close(tf);json(1,"","",",\"strategy\":\"posix-cross-volume-identity-commit\"");return 0;}
 json(0,"EINVAL","unsupported operation",NULL);return 1;
}
