export type VideoActionId = 'video.playPause'|'video.stop'|'video.seekBackward'|'video.seekForward'|'video.frameBackward'|'video.frameForward'|'video.volumeUp'|'video.volumeDown'|'video.mute'|'video.speedUp'|'video.speedDown'|'video.resetSpeed'|'video.fullscreen'|'video.exitFullscreen'|'video.capture'|'video.fitSource'|'video.fitContain'|'video.fitCover'|'video.rotateClockwise'|'video.rotateCounterclockwise'|'video.toggleSubtitles'|'video.nextSubtitle'|'video.nextAudioTrack'|'video.toggleStatistics'|'video.switchBackend'|'media.previous'|'media.next';
export type VideoShortcutScope='global'|'workspace'|'player';export type VideoShortcutInput={key:string;code:string;ctrl:boolean;alt:boolean;shift:boolean;meta:boolean;repeat:boolean};export type VideoShortcutBindings=Record<VideoActionId,string[]>;
export const VIDEO_ACTIONS:ReadonlyArray<{id:VideoActionId;label:string;scope:VideoShortcutScope;defaults:string[]}>= [
{id:'video.playPause',label:'播放 / 暂停',scope:'player',defaults:['Space','KeyK']},{id:'video.stop',label:'停止播放',scope:'player',defaults:['Shift+KeyS']},{id:'video.seekBackward',label:'快退 5 秒',scope:'player',defaults:['ArrowLeft']},{id:'video.seekForward',label:'快进 5 秒',scope:'player',defaults:['ArrowRight']},{id:'video.frameBackward',label:'后退一帧',scope:'player',defaults:['Comma']},{id:'video.frameForward',label:'前进一帧',scope:'player',defaults:['Period']},
{id:'video.volumeUp',label:'增大音量',scope:'player',defaults:['ArrowUp']},{id:'video.volumeDown',label:'减小音量',scope:'player',defaults:['ArrowDown']},{id:'video.mute',label:'静音',scope:'player',defaults:['KeyM']},{id:'video.speedUp',label:'提高速度',scope:'player',defaults:['BracketRight']},{id:'video.speedDown',label:'降低速度',scope:'player',defaults:['BracketLeft']},{id:'video.resetSpeed',label:'恢复 1×',scope:'player',defaults:['Backslash']},
{id:'video.fullscreen',label:'进入 / 退出全屏',scope:'player',defaults:['KeyF']},{id:'video.exitFullscreen',label:'退出全屏',scope:'global',defaults:['Escape']},{id:'video.capture',label:'截取当前帧',scope:'player',defaults:['Ctrl+Shift+KeyS']},{id:'video.fitSource',label:'源比例',scope:'player',defaults:['Digit1']},{id:'video.fitContain',label:'适应窗口',scope:'player',defaults:['Digit2']},{id:'video.fitCover',label:'填满窗口',scope:'player',defaults:['Digit3']},{id:'video.rotateClockwise',label:'顺时针旋转',scope:'player',defaults:['KeyR']},{id:'video.rotateCounterclockwise',label:'逆时针旋转',scope:'player',defaults:['Shift+KeyR']},
{id:'video.toggleSubtitles',label:'显示 / 隐藏字幕',scope:'player',defaults:['KeyC']},{id:'video.nextSubtitle',label:'下一字幕轨',scope:'player',defaults:['KeyV']},{id:'video.nextAudioTrack',label:'下一音轨',scope:'player',defaults:['KeyA']},{id:'video.toggleStatistics',label:'播放信息',scope:'player',defaults:['KeyI']},{id:'video.switchBackend',label:'切换播放后端',scope:'player',defaults:['KeyB']},{id:'media.previous',label:'上一个视频',scope:'workspace',defaults:['PageUp']},{id:'media.next',label:'下一个视频',scope:'workspace',defaults:['PageDown']}];
const ACTION_IDS=new Set(VIDEO_ACTIONS.map(item=>item.id)),RESERVED=new Set(['Alt+F4','Ctrl+Alt+Delete','Meta+KeyL','Meta+KeyQ','Ctrl+Shift+Escape']);const LEGACY:Record<string,VideoActionId>={'video.subtitles':'video.toggleSubtitles','video.info':'video.toggleStatistics'};const MODIFIERS=['Ctrl','Alt','Shift','Meta']as const;const normalizeKeyToken=(v:string)=>v===' '?'Space':/^\d$/.test(v)?`Digit${v}`:v.length===1?`Key${v.toUpperCase()}`:v;const canonicalizeChord=(v:string)=>{const parts=v.split('+').map(i=>i.trim()).filter(Boolean);if(!parts.length)return'';const key=normalizeKeyToken(parts.at(-1)!);const modifiers=new Set(parts.slice(0,-1).map(part=>part==='Control'?'Ctrl':part));if(!/^[A-Za-z][A-Za-z0-9]{0,63}$/.test(key)||MODIFIERS.includes(key as typeof MODIFIERS[number])||modifiers.size!==parts.length-1||[...modifiers].some(part=>!MODIFIERS.includes(part as typeof MODIFIERS[number])))return'';return[...MODIFIERS.filter(part=>modifiers.has(part)),key].join('+');};
export const shortcutChord=(i:VideoShortcutInput)=>[i.ctrl?'Ctrl':'',i.alt?'Alt':'',i.shift?'Shift':'',i.meta?'Meta':'',normalizeKeyToken(i.code||i.key)].filter(Boolean).join('+');export const isReservedVideoShortcut=(c:string)=>RESERVED.has(c);export const defaultVideoShortcutBindings=():VideoShortcutBindings=>Object.fromEntries(VIDEO_ACTIONS.map(item=>[item.id,[...item.defaults]])) as VideoShortcutBindings;
const SHORTCUT_KEY_LABELS:Record<string,string>={Space:'空格',Escape:'Esc',Enter:'回车',Tab:'Tab',Backspace:'退格',Delete:'Delete',ArrowLeft:'←',ArrowRight:'→',ArrowUp:'↑',ArrowDown:'↓',PageUp:'Page Up',PageDown:'Page Down',Comma:',',Period:'.',Slash:'/',Backslash:'\\',BracketLeft:'[',BracketRight:']',Minus:'-',Equal:'=',Meta:'Win'};
export const formatVideoShortcutChord=(chord:string)=>chord.split('+').filter(Boolean).map(part=>SHORTCUT_KEY_LABELS[part]||(/^Key[A-Z]$/.test(part)?part.slice(3):/^Digit[0-9]$/.test(part)?part.slice(5):/^Numpad/.test(part)?`数字键盘 ${part.slice(6)}`:part)).join(' + ');
export const isModifierOnlyVideoShortcutInput=(input:VideoShortcutInput)=>['Control','ControlLeft','ControlRight','Shift','ShiftLeft','ShiftRight','Alt','AltLeft','AltRight','Meta','MetaLeft','MetaRight'].includes(input.code||input.key);
export const normalizeVideoShortcutBindings=(value:unknown):VideoShortcutBindings=>{const defaults=defaultVideoShortcutBindings(),source=value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{},raw={...source};for(const[legacy,current]of Object.entries(LEGACY))if(raw[current]===undefined&&raw[legacy]!==undefined)raw[current]=raw[legacy];for(const action of VIDEO_ACTIONS){const entries=Array.isArray(raw[action.id])?raw[action.id] as unknown[]:defaults[action.id];const normalized=[...new Set(entries.map(String).map(canonicalizeChord).filter(item=>item&&!isReservedVideoShortcut(item)))].slice(0,4);defaults[action.id]=normalized.length?normalized:[...action.defaults];}return defaults;};
export const videoShortcutConflicts=(bindings:VideoShortcutBindings)=>{const owners=new Map<string,VideoActionId[]>();for(const action of VIDEO_ACTIONS)for(const chord of bindings[action.id])owners.set(chord,[...(owners.get(chord)||[]),action.id]);return[...owners].filter(([,actions])=>actions.length>1).map(([chord,actions])=>({chord,actions}));};const scopeAllows=(action:VideoShortcutScope,current:VideoShortcutScope)=>action==='global'||action==='workspace'&&current!=='global'||action==='player'&&current==='player';
export const resolveVideoShortcut=(input:VideoShortcutInput,bindings:VideoShortcutBindings,{editable=false,scope='player'}:{editable?:boolean;scope?:VideoShortcutScope}={}):VideoActionId|null=>{const chord=shortcutChord(input);if(isReservedVideoShortcut(chord)||(editable&&chord!=='Escape'))return null;for(const action of VIDEO_ACTIONS)if(scopeAllows(action.scope,scope)&&bindings[action.id].includes(chord))return action.id;return null;};
export const shouldDeferVideoShortcutToFocusedControl=(input:VideoShortcutInput,focusedControl:boolean)=>focusedControl&&(input.key==='Enter'||input.key===' '||input.code==='Enter'||input.code==='Space');
const REPEATABLE_VIDEO_ACTIONS:ReadonlySet<VideoActionId>=new Set(['video.seekBackward','video.seekForward','video.frameBackward','video.frameForward','video.volumeUp','video.volumeDown','video.speedUp','video.speedDown']);export const videoShortcutAllowsRepeat=(action:VideoActionId)=>REPEATABLE_VIDEO_ACTIONS.has(action);
export const bindingsForArrowMode=(bindings:VideoShortcutBindings,mode:'seek'|'navigate'):VideoShortcutBindings=>{const result=normalizeVideoShortcutBindings(bindings);if(mode==='navigate'){result['video.seekBackward']=result['video.seekBackward'].filter(item=>item!=='ArrowLeft');result['video.seekForward']=result['video.seekForward'].filter(item=>item!=='ArrowRight');result['media.previous']=[...new Set([...result['media.previous'],'ArrowLeft'])];result['media.next']=[...new Set([...result['media.next'],'ArrowRight'])];}return result;};
export const exportVideoShortcuts=(bindings:VideoShortcutBindings)=>JSON.stringify({schemaVersion:2,kind:'photoflow-video-shortcuts',bindings:normalizeVideoShortcutBindings(bindings)},null,2);export const importVideoShortcuts=(text:string)=>{const value=JSON.parse(text)as unknown;if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('快捷键配置格式无效');const document=value as Record<string,unknown>;if((document.schemaVersion!==1&&document.schemaVersion!==2)||document.kind!=='photoflow-video-shortcuts'||Object.keys(document).some(key=>!['schemaVersion','kind','bindings'].includes(key))||!document.bindings||typeof document.bindings!=='object'||Array.isArray(document.bindings))throw new Error('快捷键配置格式无效');const raw=document.bindings as Record<string,unknown>;if(Object.keys(raw).some(key=>!ACTION_IDS.has((LEGACY[key]||key)as VideoActionId))||Object.values(raw).some(entries=>!Array.isArray(entries)||entries.length>4||entries.some(entry=>typeof entry!=='string'||!canonicalizeChord(entry)||isReservedVideoShortcut(canonicalizeChord(entry)))))throw new Error('快捷键配置格式无效');const bindings=normalizeVideoShortcutBindings(raw),conflicts=videoShortcutConflicts(bindings);if(conflicts.length)throw new Error(`快捷键冲突：${conflicts[0].chord}`);return bindings;};export const shortcutInputFromKeyboardEvent=(e:Pick<KeyboardEvent,'key'|'code'|'ctrlKey'|'altKey'|'shiftKey'|'metaKey'|'repeat'>):VideoShortcutInput=>({key:e.key,code:e.code||e.key,ctrl:e.ctrlKey,alt:e.altKey,shift:e.shiftKey,meta:e.metaKey,repeat:e.repeat});
